# Generated by Django 3.1 on 2022-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
