# Generated by Django 3.1 on 2022-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_App', '0003_auto_20220105_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
    ]
